In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [3]:
datasets = [np.loadtxt("../Data/tictac_single.txt"), \
            np.loadtxt("../Data/tictac_final.txt")]

In [4]:
kf = KFold(n_splits=10)

net_hidden_layers = (75, 50, 25)
net_learning_rate = 0.01
epochs = 250
datasets_names = ['Single', 'Final']
conf_matrix = []

for ds_cnt, ds in enumerate(datasets):
    X = ds[:, :9]
    y = ds[:, 9:]
    X = StandardScaler().fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)
    
    net = MLPClassifier(activation='tanh',
                    n_iter_no_change=1000)
    
    net.set_params(hidden_layer_sizes=net_hidden_layers, 
                       learning_rate_init=net_learning_rate,
                       max_iter=epochs)
    f = 1
    avg_score = 0
    print(f'Dataset: {datasets_names[ds_cnt]}')
    for train_index, validation_index in kf.split(X_train):
        X_train2, X_validation = X_train[train_index,:], X_train[validation_index,:]
        y_train2, y_validation = y_train[train_index,:], y_train[validation_index,:]
        
        
        net.fit(X_train2, y_train2.ravel())
        y_train_pred = net.predict(X_train2)
        y_val_pred = net.predict(X_validation)
        acc_score = accuracy_score(y_train2, y_train_pred)
        test_score = accuracy_score(y_validation, y_val_pred)
        
        print('--------------------------------------')
        print(f'Fold {f}')
        print(f'Hidden Layer Architecture: {net_hidden_layers}')
        print(f'Learning Rate: {net_learning_rate}')
        print(f'Number of Epochs: {epochs}')
        print(f'Train Accuracy = {np.round(acc_score*100,2)}%')
        print(f'Test Accuracy = {np.round(test_score*100,2)}%')
        print('--------------------------------------')
        
        avg_score += test_score
        f += 1
        
    avg_score /= 10
    print(f'Average score for all the folds is {avg_score}')
    
    final_net = MLPClassifier(activation='tanh',
                              n_iter_no_change=1000)
    
    final_net.set_params(hidden_layer_sizes=net_hidden_layers, 
                         learning_rate_init=net_learning_rate,
                         max_iter=epochs)
    
    final_net.fit(X_train, y_train.ravel())
    final_pred = final_net.predict(X_test)
    final_acc = accuracy_score(y_test, final_pred)
    print(f'Final Accuracy score for the MLP: {np.round(final_acc*100, 2)}')
    conf_matrix += [confusion_matrix(y_test, final_pred)]
    

Dataset: Single


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 1
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 89.76%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 2
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 87.36%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 3
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 85.4%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 4
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 90.63%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 5
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 90.63%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 6
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 87.77%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 7
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 89.3%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 8
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 87.77%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 9
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 89.08%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 10
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 89.08%
--------------------------------------
Average score for all the folds is 0.8868039501098839


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


Final Accuracy score for the MLP: 89.01
Dataset: Final


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 1
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 98.51%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 2
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 100.0%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 3
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 100.0%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 4
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 97.01%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 5
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 97.01%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 6
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 98.51%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 7
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 98.51%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 8
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 100.0%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 9
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 97.01%
--------------------------------------


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


--------------------------------------
Fold 10
Hidden Layer Architecture: (75, 50, 25)
Learning Rate: 0.01
Number of Epochs: 250
Train Accuracy = 100.0%
Test Accuracy = 98.51%
--------------------------------------
Average score for all the folds is 0.9850746268656716
Final Accuracy score for the MLP: 99.31


C:\Users\andre\anaconda3\envs\eee4773\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


In [5]:
print('Confusion matrix for the "Single" dataset:')
print(conf_matrix[0])
print('\nConfusion matrix for the "Final" dataset:')
print(conf_matrix[1])

Confusion matrix for the "Single" dataset:
[[443   2   3   2   4   3   3   0   6]
 [  5 215   1   2   4   5   4   1   5]
 [  8   2 273   3   7   2   7   4   1]
 [  5   6   0 128   5   3   5   2   2]
 [  6   7   8   6 305   2   2   0   3]
 [  5   2   0   2   5  82   1   2   1]
 [ 12   2   1   4   0   1 134   0   0]
 [  5   2   0   0   0   0   1  52   0]
 [  9   2   6   0   2   2   3   0 118]]

Confusion matrix for the "Final" dataset:
[[ 85   2]
 [  0 201]]
